services:
  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: investor-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.3"
      - fromEnvGroup: infinity-fintech-secrets

  - type: staticSite
    name: investor-app-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: url

databases:
  - name: investor-db
