# In D:/investor-app/render.yaml

# This section defines the two types of resources: databases and services
databases:
  - name: investor-db
    plan: free # The database has a free plan

services:
  #--------------------
  # 1. The Backend Web Service (Django)
  #--------------------
  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    plan: free # This is a 'web' service, which has a free plan.
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investor-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9" # Updated to your version
      - key: RENDER_FRONTEND_URL
        fromService:
          type: static_site # This refers to the service type below
          name: investor-app-frontend
          property: url
      - fromEnvGroup: infinity-fintech-secrets # This is for your Cloudinary keys

  #--------------------
  # 2. The Frontend Static Site (React)
  #--------------------
  - type: static_site # Using the correct 'static_site' type
    name: investor-app-frontend
    rootDir: frontend
    plan: free # 'static_site' type has a free plan.
    buildCommand: "npm install && npm run build"
    # The 'publishDir' is the key that static_site uses.
    publishDir: ./dist
    # The rewrite rule for SPAs
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: url

# Ensure the Environment Group is defined if used
envVarGroups:
  - name: infinity-fintech-secrets