# In D:/investor-app/render.yaml

# This 'previews' key enables Pull Request Previews, a nice feature
previews: true

# This 'databases' key defines your PostgreSQL instance
databases:
  - name: investor-db
    plan: free # Explicitly use the free plan for the database
    # postgresqlMajorVersion: 15 # Optional: specify a version

# This 'services' key defines your applications
services:
  #--------------------
  # 1. The Backend Web Service
  #--------------------
  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    plan: free # Explicitly use the free plan for the web service
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: investor-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      # Link to the frontend URL for CORS. Render fills this in.
      - key: RENDER_FRONTEND_URL
        fromService:
          type: static_site
          name: investor-app-frontend
          property: url
      # Link to your Cloudinary secrets. This is the correct way.
      - fromEnvGroup: infinity-fintech-secrets

  #--------------------
  # 2. The Frontend Static Site
  #--------------------
  - type: static_site # This was the source of the error in the screenshot
    name: investor-app-frontend
    rootDir: frontend
    plan: free # Explicitly use the free plan for the static site
    buildCommand: "npm install && npm run build"
    # For a static site, there is no startCommand. Instead, we specify the directory to publish.
    # publishPath: "dist" # The 'publishDir' key seems to have been deprecated for `static_site`
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: url

# This 'envVarGroups' key references the secrets group you created.
envVarGroups:
  - name: infinity-fintech-secrets
    # envVars are defined on your Render dashboard, not here