# In D:/investor-app/render.yaml

services:
  #--------------------
  # 1. Backend Web Service (Django)
  #--------------------
  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    # --- THIS IS THE CORRECTED DATABASE CONNECTION ---
    databases:
      - name: investor-db # This name must match the database defined below
        property: connectionString # This injects it as DATABASE_URL
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: RENDER_FRONTEND_URL
        fromService:
          type: web
          name: investor-app-frontend
          property: host
      # Link to your secret variables using an Environment Group
      - fromEnvGroup: infinity-fintech-secrets

  #--------------------
  # 2. Frontend Web Service (React/Vite)
  #--------------------
  - type: web
    name: investor-app-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s dist"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: host

# This defines the PostgreSQL database itself
databases:
  - name: investor-db
    plan: free

# Defines the secret group to pull variables from
envVarGroups:
  - name: infinity-fintech-secrets