# In D:/investor-app/render.yaml

services:
  #--------------------
  # 1. The Backend Web Service
  #--------------------
  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investor-db # <-- Ensure this matches the name of your Render DB
          property: internalConnectionString
      # Environment variables for your secrets
      # To set these, go to your Account Settings > Blueprints
      # and create an "Environment Group" with these secret keys.
      # Then add 'envGroup: your-group-name' here.
      - key: SECRET_KEY
        generateValue: true # Or pull from an env group
      - key: RENDER_FRONTEND_URL
        value: "https://investor-app-frontend.onrender.com" # Default frontend name
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9" # Set your Python version here

  #--------------------
  # 2. The Frontend Static Site (Corrected Type)
  #--------------------
  - type: static_site # Use 'static_site' for React/Vite
    name: investor-app-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: "dist" # The output folder for Vite's build
    # Rewrite rule for single-page applications
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    # Environment variable for the frontend to find the backend
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: url