# In D:/investor-app/render.yaml

# This section defines all the pieces of our application.
# Render will build them in order.
services:
  - type: psql
    name: investor-db

  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: investor-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a random secure key
      - key: PYTHON_VERSION
        value: "3.11.9" # Or your specific version
      - key: RENDER_FRONTEND_URL
        fromService:
          type: staticSite
          name: investor-app-frontend
          property: url

  #--------------------
  # 3. The Frontend Static Site
  #--------------------
  - type: staticSite # CORRECTED: Use camelCase 'staticSite'
    name: investor-app-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: url