# In D:/investor-app/render.yaml

# This section defines your database. It's separate from services.
databases:
  - name: investor-db
    plan: free

# This section defines your two applications.
services:
  #--------------------
  # 1. Backend Web Service (Django)
  #--------------------
  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: investor-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      # This CORRECTLY links your Environment Group
      - fromEnvGroup: infinity-fintech-secrets
      - key: RENDER_FRONTEND_URL
        fromService:
          type: web
          name: investor-app-frontend
          property: host # The host is the URL

  #--------------------
  # 2. Frontend Web Service (React/Vite)
  #--------------------
  - type: web
    name: investor-app-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s dist"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: host # The host is the URL

# Define the name of your secrets group
envVarGroups:
  - name: infinity-fintech-secrets