# In D:/investor-app/render.yaml

databases:
  - name: investor-db
    plan: free

services:
  #--------------------
  # 1. Backend Web Service (Django)
  #--------------------
  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    plan: free # 'web' service type has a free tier
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investor-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      - fromEnvGroup: infinity-fintech-secrets # For your Cloudinary keys

  #--------------------
  # 2. Frontend Web Service (React/Vite)
  # CORRECTED: This must also be 'type: web'
  #--------------------
  - type: web
    name: investor-app-frontend
    env: node # Use the Node.js environment
    rootDir: frontend
    plan: free # 'web' service on the free tier also works for simple Node servers
    buildCommand: "npm install && npm run build"
    # The start command installs 'serve' and runs the built 'dist' folder.
    # The '-s' flag handles the SPA rewrite rule automatically.
    startCommand: "npm install -g serve && serve -s dist"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: url

# Define your secrets group
envVarGroups:
  - name: infinity-fintech-secrets