# In D:/investor-app/render.yaml

# Define the PostgreSQL database
databases:
  - name: investor-db
    plan: free

# Define the backend and frontend services
services:
  # --------------------
  # 1. Backend Web Service (Django)
  # --------------------
  - type: web
    name: investor-app-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: investor-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: RENDER_FRONTEND_URL
        fromService:
          type: web
          name: investor-app-frontend
          property: url
      - fromEnvGroup: infinity-fintech-secrets

  # --------------------
  # 2. Frontend Static Site (React / Vite / Next.js static build)
  # --------------------
  - type: web
    name: investor-app-frontend
    env: static
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist   # or "build" depending on framework
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: investor-app-backend
          property: url

# Secrets group reference
envVarGroups:
  - name: infinity-fintech-secrets
