# Generated by Django 5.2.5 on 2025-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_shop_profit_margin_cashier_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
