# Generated by Django 5.2.5 on 2025-08-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_investor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='investor',
        ),
        migrations.AddField(
            model_name='shop',
            name='investors',
            field=models.ManyToManyField(related_name='shops', to='shops.investor'),
        ),
    ]
