# Generated by Django 5.2.5 on 2025-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_dailysale_expenditure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='profit_margin',
        ),
        migrations.AddField(
            model_name='cashier',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
