# Generated by Django 5.2.5 on 2025-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_investor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='can_view_all_shops',
            field=models.BooleanField(default=False, help_text='Designates whether this investor can view all shops in their portfolio.'),
        ),
    ]
