# Generated by Django 5.2.5 on 2025-08-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_investor_can_view_all_shops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'permissions': [('can_view_full_dashboard', 'Can view all shops and full details on the dashboard')]},
        ),
    ]
