# Generated by Django 5.2.5 on 2025-08-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_cashier_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysale',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter total expenses for the day', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='calculated_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
